import './globals.css';
import { Geist, Geist_Mono, Gwendolyn } from 'next/font/google';
import { FloatingWhatsApp } from '../components/FloatingWhatsapp/FlotaingWhatsApp';


// Load fonts with variables
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const gwendolyn = Gwendolyn({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-gwendolyn',
});

// Metadata export for Next.js
export const metadata = {
  title: 'Open Door Sports',
  description: 'Generated by Open Door sports',
};

export const viewport = {
  width: 'device-width',
  initialScale: 1.0,
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${gwendolyn.variable}`}>
      <body className="antialiased relative">
   
        {children}
        {/* ✅ Floating WhatsApp button appears on all pages */}
        <FloatingWhatsApp />
      </body>
    </html>
  );
}
